# Generated by Django 5.1.7 on 2025-03-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beys_world', '0003_assistblade_bit_lockchips_mainblade_ratchet_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LockChips',
            new_name='LockChip',
        ),
        migrations.AlterField(
            model_name='bit',
            name='stat_dash',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dash'),
        ),
    ]
