# Generated by Django 5.1.7 on 2025-03-19 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beys_world', '0004_rename_lockchips_lockchip_alter_bit_stat_dash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratchet',
            name='spin_direction',
        ),
    ]
