# Generated by Django 5.1.7 on 2025-03-19 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beys_world', '0005_remove_ratchet_spin_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bit',
            name='spin_direction',
        ),
    ]
