# Generated by Django 5.1.7 on 2025-03-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beys_world', '0006_remove_bit_spin_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistblade',
            name='name',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Name'),
        ),
    ]
