# Generated by Django 5.1.7 on 2025-04-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beys_world', '0007_alter_assistblade_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainblade',
            name='link_fandom',
            field=models.URLField(max_length=100, verbose_name='Link Fandom'),
        ),
    ]
