# Generated by Django 5.1.7 on 2025-04-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beys_world', '0008_alter_mainblade_link_fandom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistblade',
            name='link_fandom',
            field=models.URLField(max_length=100, verbose_name='Link Fandom'),
        ),
        migrations.AlterField(
            model_name='bit',
            name='link_fandom',
            field=models.URLField(max_length=100, verbose_name='Link Fandom'),
        ),
        migrations.AlterField(
            model_name='blade',
            name='link_fandom',
            field=models.URLField(max_length=100, verbose_name='Link Fandom'),
        ),
        migrations.AlterField(
            model_name='lockchip',
            name='link_fandom',
            field=models.URLField(max_length=100, verbose_name='Link Fandom'),
        ),
        migrations.AlterField(
            model_name='ratchet',
            name='link_fandom',
            field=models.URLField(max_length=100, verbose_name='Link Fandom'),
        ),
    ]
