# Generated by Django 5.1.7 on 2025-04-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beys_world', '0009_alter_assistblade_link_fandom_alter_bit_link_fandom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistblade',
            name='image',
            field=models.ImageField(blank=True, upload_to='pictures/assist_blades/%Y/%m/%d', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='assistblade',
            name='link_fandom',
            field=models.URLField(blank=True, max_length=100, verbose_name='Link Fandom'),
        ),
        migrations.AlterField(
            model_name='bit',
            name='image',
            field=models.ImageField(blank=True, upload_to='pictures/bits/%Y/%m/%d', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='bit',
            name='link_fandom',
            field=models.URLField(blank=True, max_length=100, verbose_name='Link Fandom'),
        ),
        migrations.AlterField(
            model_name='blade',
            name='link_fandom',
            field=models.URLField(blank=True, max_length=100, verbose_name='Link Fandom'),
        ),
        migrations.AlterField(
            model_name='lockchip',
            name='image',
            field=models.ImageField(blank=True, upload_to='pictures/lock_chips/%Y/%m/%d', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='lockchip',
            name='link_fandom',
            field=models.URLField(blank=True, max_length=100, verbose_name='Link Fandom'),
        ),
        migrations.AlterField(
            model_name='mainblade',
            name='image',
            field=models.ImageField(blank=True, upload_to='pictures/main_blades/%Y/%m/%d', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='mainblade',
            name='link_fandom',
            field=models.URLField(blank=True, max_length=100, verbose_name='Link Fandom'),
        ),
        migrations.AlterField(
            model_name='ratchet',
            name='image',
            field=models.ImageField(blank=True, upload_to='pictures/ratchets/%Y/%m/%d', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='ratchet',
            name='link_fandom',
            field=models.URLField(blank=True, max_length=100, verbose_name='Link Fandom'),
        ),
    ]
