# Generated by Django 5.1.7 on 2025-04-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beys_world', '0010_alter_assistblade_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistblade',
            name='link_fandom',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Link Fandom'),
        ),
        migrations.AlterField(
            model_name='bit',
            name='link_fandom',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Link Fandom'),
        ),
        migrations.AlterField(
            model_name='blade',
            name='link_fandom',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Link Fandom'),
        ),
        migrations.AlterField(
            model_name='lockchip',
            name='link_fandom',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Link Fandom'),
        ),
        migrations.AlterField(
            model_name='mainblade',
            name='link_fandom',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Link Fandom'),
        ),
        migrations.AlterField(
            model_name='ratchet',
            name='link_fandom',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Link Fandom'),
        ),
    ]
